Do not show breadcrumbs for worldwide organisation and office pages
alphagov/government-frontend pull request #2812
Opened 2023-06-05 16:28 UTC by jkempster34

We don't want to show breadcrumbs on the worldwide organisation and office pages.

This follows the existing pattern of setting the @do_not_show_breadcrumbs variable.

It might be nice to move these into the derived classes of `ContentItemPresenter` in future as part of a wider refactor.

---

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

2023-06-05 17:05 UTC, CristinaRO submitted a review, later dismissed

2023-06-06 09:09 UTC, brucebolt approved these changes
The changes all make sense to me.

Probably worth getting the owning team to review this too.

2023-06-06 10:36 UTC, chao-xian requested changes
Thanks for the URLs @jkempster34. I can see that the spacing above the logo isn't right. It should be like on https://webarchive.nationalarchives.gov.uk/ukgwa/20220203051007/https://www.gov.uk/world/organisations/british-embassy-paris/office/british-embassy

2023-06-06 10:50 UTC, jkempster34 commented
> Thanks for the URLs @jkempster34. I can see that the spacing above the logo isn't right. It should be like on https://webarchive.nationalarchives.gov.uk/ukgwa/20220203051007/https://www.gov.uk/world/organisations/british-embassy-paris/office/british-embassy

Good spot! Fixed in a separate commit.

I've also added some examples to the development controller in another commit

2023-06-06 11:14 UTC, chao-xian approved these changes
Thanks @jkempster34 !

2023-06-06 11:20 UTC, merged